apiVersion: v1
kind: Service
metadata:
  name: svc-tcp
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"        
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  ports:
  - name: dns
    protocol: TCP
    port: 53
    targetPort: 53
--- 
apiVersion: v1
kind: Service
metadata:
  name: svc-udp
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  ports:
  - name: dns
    protocol: UDP
    port: 53
    targetPort: 53

