apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: carol 
  namespace: dev
subjects:
- kind: ServiceAccount 
  name: carol
  apiGroup: ""
roleRef:
   kind: ClusterRole
   name: admin
   apiGroup: ""

