apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ken 
  namespace: dev
subjects:
- kind: ServiceAccount 
  name: ken
  apiGroup: ""
roleRef:
   kind: ClusterRole
   name: view
   apiGroup: ""

