apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-reader 
subjects:
- kind: Group 
  name: system:serviceaccounts:prometheus
  apiGroup: ""
roleRef:
   kind: ClusterRole
   name: pod-reader
   apiGroup: ""

