apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

## PrefixSuffixTransformer
##namePrefix: dev-

## NamespaceTransformer
namespace: hipster-shop 

## LabelTransformer
commonLabels:
  environment: dev

bases:
- ../../base
