apiVersion: v1
kind: Service
metadata:
  name: exporter-svc
  labels:
    app: exporter
spec:
  selector:
    app: exporter
  ports:
  - protocol: TCP
    name: exporter
    port: 9113
#    targetPort: 9113
