environments:
  develop:
    values:
      - domain: harbor.{{ env "SERVICE_IP" }}.nip.io 
  production:
    values:
      - domain: IP.xip.io

repositories:
- name: stable
  url: https://charts.helm.sh/stable
- name: jetstack
  url:  https://charts.jetstack.io
- name: harbor
  url: https://helm.goharbor.io

templates:
  template: &template
    missingFileHandler: Info
    values:
    - ./values/{{`{{ .Release.Name }}`}}.yaml.gotmpl

releases:
- name: nginx-ingress 
  chart: stable/nginx-ingress
  namespace: nginx-ingress
  version: 1.41.3
  wait: true
  timeout: 280
  <<: *template
- name: cert-manager
  chart: jetstack/cert-manager
  namespace: cert-manager
  version: 0.16.1
  needs:
  - nginx-ingress/nginx-ingress
  labels:
    app: cert-manager
  wait: true
  timeout: 280
  values:
    - installCRDs: true 
  hooks:
    # This hook adds the CRDs
#    - events: ["presync"]
#      showlogs: true
#      command: "kubectl"
#      args: ["apply", "--validate=false", "-f", "https://github.com/jetstack/cert-manager/releases/download/v0.16.1/cert-manager.crds.yaml"]
    - events: ["postsync"]
      showlogs: true
      command: "kubectl"
      args: ["apply", "-f", "../cert-manager/clusterissuer.yaml", "-n", "cert-manager"]
  <<: *template
- name: harbor
  chart: harbor/harbor
  namespace: harbor
  version: 1.5.2
  labels:
    app: harbor
  needs:
  - nginx-ingress/nginx-ingress
  - cert-manager/cert-manager  
  hooks:
    # This hook adds the CRDs
    - events: ["prepare"]
      showlogs: true
      command: "/bin/sh"
      args: ["-c", "export SERVICE_IP=$(kubectl get svc --namespace nginx-ingress nginx-ingress-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')"]
  <<: *template
