apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: server
        image: itokareva/hipster-paymentservice:2.0
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
    type: RollingUpdate

