environments:
  develop:
    values:
      - domain: harbor.{{ env "SERVICE_IP" }}.nip.io 
  production:
    values:
      - domain: IP.xip.io

repositories:
- name: stable
  url: https://charts.helm.sh/stable
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts

templates:
  template: &template
    missingFileHandler: Info
    values:
    - ./values/{{`{{ .Release.Name }}`}}.yaml.gotmpl

releases:
- name: nginx-ingress 
  chart: stable/nginx-ingress
  namespace: nginx-ingress
  version: 1.41.3
  labels:
    app: nginx-ingress
  wait: true
  timeout: 280
  <<: *template
- name: kube-prometheus-stack
  chart: prometheus-community/kube-prometheus-stack
#  version: 12.11.3 
  labels:
    app: kube-prometheus-stack
  needs:
  - nginx-ingress/nginx-ingress
  <<: *template
