---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: shop.35.228.225.177.nip.io
    http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 8080
        path: /

